### ISSUE TITLE
Is it possible to enable ALL simconnect variables at once?

### ISSUE THREAD

**Issue by kebelig** [marcosox/fsx-saas#1]

**Comment by marcosox** [comment]
Unfortunately, Simconnect does not expose its list of sim variables, nor a method to set them all at once.

The only way to enable all the simconnect variables is to add them manually one by one to the `DATA_DEFINITION_ID.AIRCRAFT_DETAIL` data definition.

If someone wants to undertake the effort and map [all simconnect variables strings and units](https://docs.microsoft.com/en-us/previous-versions/microsoft-esp/cc526981(v=msdn.10)) in a class, the program can easily be adapted to loop over them and add them all to a single request.
